name: Node.js

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'wiki/**'

jobs:
  unit_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
   
    steps:
    - uses: actions/checkout@v2
    - name: Chmod
      run: chmod +x ./install_db_shelter.sh
      working-directory: /home/runner/work/bmstu_teamdev_shelter/bmstu_teamdev_shelter/db/
      shell: bash
    - name: Install DB
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: ./install_db_shelter.sh $POSTGRES_PASSWORD
      working-directory: /home/runner/work/dr-td/dr-td/db/
      shell: bash
    - name: Create file env
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        ENV_SECRET_KEY: ${{ secrets.ENV_SECRET_KEY }}
      run: echo -e "PORT=5000\nDB_NAME=$POSTGRES_DB_NAME\nDB_USER=$POSTGRES_USER\nDB_PASSWORD=$POSTGRES_PASSWORD\nDB_HOST=$POSTGRES_HOST\nDB_PORT=$POSTGRES_PORT\nSECRET_KEY=$ENV_SECRET_KEY" > .env
      working-directory: /home/runner/work/bmstu_teamdev_shelter/bmstu_teamdev_shelter/src/server

    - name: Run test
      run: | 
        npm install
        npm test
      working-directory: /home/runner/work/bmstu_teamdev_shelter/bmstu_teamdev_shelter/src/server
